apiVersion: v1
entries:
  pingaccess:
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-09T13:31:52.84773-05:00"
    description: A Sample PingAccess Helm chart
    digest: 8b650ce9c728cf778914d2c8cb139caaa6d28ec44a8217ed3df8b9babfda5642
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingaccess-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-09T13:31:52.846794-05:00"
    description: A Sample PingAccess Helm chart
    digest: 7fd4d7051b374fbe14b6556b52bb491838585effa8e518a8a6bb0fb7ffa76d0e
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingaccess-0.0.5.tgz
    version: 0.0.5
  pingcentral:
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-09T13:31:52.849912-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: b50a6b19705ac0c7d47fbee36965efa748eb78a55df62066325b136076c16699
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingcentral-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-09T13:31:52.848886-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: 152fc218371d853ce5955265f0fea61765d48970484caef72ed04972d8bd7d8e
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingcentral-0.0.18.tgz
    version: 0.0.18
  pingdataconsole:
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-09T13:31:52.850627-05:00"
    description: A Sample PingDataConsole Helm chart
    digest: 1516fd9024b975f2f8164ef417d71085f77b3b492f2cac723b9b59ed68bfe468
    home: https://www.pingidentity.com/
    name: pingdataconsole
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingdataconsole-0.1.2.tgz
    version: 0.1.2
  pingdatasync:
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-09T13:31:52.851279-05:00"
    description: A Sample PingDataSync Helm chart - CPrice edits
    digest: bff337aaacb56464485ada991a36b9f8ed85e6e24251714fe13a6cd940033850
    home: https://www.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingdatasync-0.0.3.tgz
    version: 0.0.3
  pingdirectory:
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-09T13:31:52.852263-05:00"
    description: A Sample PingDirectory Helm chart - CPrice edits
    digest: adbb7295f951cd47ba95442e438d5b33bb2383dc4db9ce01739706919e324293
    home: https://www.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingdirectory-0.0.9.tgz
    version: 0.0.9
  pingfederate:
  - apiVersion: v1
    appVersion: 10.1.0
    created: "2020-10-09T13:31:52.853464-05:00"
    description: A Sample PingFederate Helm chart with clustering - CPrice Edits
    digest: 5d90e47d7c13cfcc89d36af1bdcd7fab12a5e5c358d707e760cd238f89be7739
    home: https://www.pingidentity.com/
    name: pingfederate
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/pingfederate-0.0.4.tgz
    version: 0.0.4
generated: "2020-10-09T13:31:52.844504-05:00"
