apiVersion: v1
entries:
  pingaccess:
  - apiVersion: v2
    appVersion: "6.1"
    created: "2020-10-22T08:14:51.687853-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingAccess Helm chart
    digest: be97fa2731a2bd7c789ed60f03dbd53558369178910f2018f177bd58f966dd20
    home: https://devops.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-22T08:14:51.686344-05:00"
    description: A Sample PingAccess Helm chart
    digest: 8b650ce9c728cf778914d2c8cb139caaa6d28ec44a8217ed3df8b9babfda5642
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-22T08:14:51.685408-05:00"
    description: A Sample PingAccess Helm chart
    digest: 7fd4d7051b374fbe14b6556b52bb491838585effa8e518a8a6bb0fb7ffa76d0e
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.5.tgz
    version: 0.0.5
  pingcentral:
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-22T08:14:51.689413-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: b50a6b19705ac0c7d47fbee36965efa748eb78a55df62066325b136076c16699
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-22T08:14:51.68867-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: 152fc218371d853ce5955265f0fea61765d48970484caef72ed04972d8bd7d8e
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.18.tgz
    version: 0.0.18
  pingdataconsole:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-22T08:14:51.690523-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Standalone PingDataConsole Helm chart
    digest: a0b6a8635c090a7f67980bfff9a05b45b4170ecbaf5580e7082b43b4700d585d
    home: https://devops.pingidentity.com/
    name: pingdataconsole
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdataconsole-0.1.0.tgz
    version: 0.1.0
  pingdatasync:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-22T08:14:51.691892-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDataSync Helm chart
    digest: 8d9a2477cdbb17402354c682aab0ab72006340a4e7c754d63e3600cd33ac7c20
    home: https://devops.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-22T08:14:51.691-05:00"
    description: A Sample PingDataSync Helm chart - CPrice edits
    digest: bff337aaacb56464485ada991a36b9f8ed85e6e24251714fe13a6cd940033850
    home: https://www.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.0.3.tgz
    version: 0.0.3
  pingdelegator:
  - apiVersion: v2
    appVersion: "4.2"
    created: "2020-10-22T08:14:51.692799-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDelegator Helm chart
    digest: 60b96c7ff7a4177ad1fb6d62efccc1e109b95913f7c6e58b354385a36dfe2397
    home: https://devops.pingidentity.com/
    name: pingdelegator
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdelegator-0.1.0.tgz
    version: 0.1.0
  pingdirectory:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-22T08:14:51.694425-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDirectory Helm chart
    digest: 98841806701a8d52fb7656ca9bd7013d183862beaffea0359d214e7bf4c84c7e
    home: https://devops.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-22T08:14:51.693363-05:00"
    description: A Sample PingDirectory Helm chart - CPrice edits
    digest: adbb7295f951cd47ba95442e438d5b33bb2383dc4db9ce01739706919e324293
    home: https://www.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.0.9.tgz
    version: 0.0.9
  pingfederate:
  - apiVersion: v1
    appVersion: 10.1.0
    created: "2020-10-22T08:14:51.695165-05:00"
    description: A Sample PingFederate Helm chart with clustering - CPrice Edits
    digest: 5d90e47d7c13cfcc89d36af1bdcd7fab12a5e5c358d707e760cd238f89be7739
    home: https://www.pingidentity.com/
    name: pingfederate
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-0.0.4.tgz
    version: 0.0.4
  pingfederate-admin:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-22T08:14:51.696185-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Admin Helm chart with clustering
    digest: a274380c77c6ed0827a3a5dedc471e8f7e4262da99eb98b0705881a216b0624e
    home: https://devops.pingidentity.com/
    name: pingfederate-admin
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-admin-0.1.0.tgz
    version: 0.1.0
  pingfederate-engine:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-22T08:14:51.698845-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Engine Helm chart with clustering
    digest: 24e26d6c084084ccf803d774c797d8b15c8c4f477156c563d4f43d5cbfd62e4c
    home: https://devops.pingidentity.com/
    name: pingfederate-engine
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-engine-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-22T08:14:51.684726-05:00"
