apiVersion: v1
entries:
  pingaccess:
  - apiVersion: v2
    appVersion: "6.1"
    created: "2020-10-22T07:39:46.136883-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingAccess Helm chart
    digest: 592836a049bfcfc7a591b182e3c227b7bf22e6e60813fa383e56cf4603d58aff
    home: https://devops.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-22T07:39:46.135846-05:00"
    description: A Sample PingAccess Helm chart
    digest: 8b650ce9c728cf778914d2c8cb139caaa6d28ec44a8217ed3df8b9babfda5642
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-22T07:39:46.135287-05:00"
    description: A Sample PingAccess Helm chart
    digest: 7fd4d7051b374fbe14b6556b52bb491838585effa8e518a8a6bb0fb7ffa76d0e
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.5.tgz
    version: 0.0.5
  pingcentral:
  - apiVersion: v2
    appVersion: "1.5"
    created: "2020-10-22T07:39:46.13919-05:00"
    dependencies:
    - name: pingdevops
      repository: https://helm.pingidentity.com/devops
      version: 0.1.0
    description: A Sample PingCentral Helm chart
    digest: 7965dd734d1e34478099e2612fd95ffe9d5e0c48e91dbd0db638ee62b583197a
    home: https://devops.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-22T07:39:46.138238-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: b50a6b19705ac0c7d47fbee36965efa748eb78a55df62066325b136076c16699
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-22T07:39:46.13759-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: 152fc218371d853ce5955265f0fea61765d48970484caef72ed04972d8bd7d8e
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.18.tgz
    version: 0.0.18
  pingdataconsole:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-22T07:39:46.140128-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Standalone PingDataConsole Helm chart
    digest: c2e35567c33ef7268d6859c8e493ba08993db5a4c27f94d820364222d69f437c
    home: https://devops.pingidentity.com/
    name: pingdataconsole
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdataconsole-0.1.0.tgz
    version: 0.1.0
  pingdatagovernance:
  - apiVersion: v2
    appVersion: 8.1.0
    created: "2020-10-22T07:39:46.141105-05:00"
    dependencies:
    - name: pingdevops
      repository: https://helm.pingidentity.com/devops
      version: 0.1.0
    description: A Standalone PingDataGovernance Helm chart
    digest: 390a2aecd84cf71e6617e00f27e577e9917058ae45139e415d55129d25869b90
    home: https://devops.pingidentity.com/
    name: pingdatagovernance
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdatagovernance-0.1.0.tgz
    version: 0.1.0
  pingdatasync:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-22T07:39:46.142968-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDataSync Helm chart
    digest: 887259cda0a23e8f63edf09162d9095fcc622ed1ed354c9666d9e7957679472b
    home: https://devops.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-22T07:39:46.14168-05:00"
    description: A Sample PingDataSync Helm chart - CPrice edits
    digest: bff337aaacb56464485ada991a36b9f8ed85e6e24251714fe13a6cd940033850
    home: https://www.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.0.3.tgz
    version: 0.0.3
  pingdelegator:
  - apiVersion: v2
    appVersion: "4.2"
    created: "2020-10-22T07:39:46.144457-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDelegator Helm chart
    digest: dd50ff922f3af5c1f40f8447697ef1d31eb411a4eb2c87dd9d3ba56c42f5171c
    home: https://devops.pingidentity.com/
    name: pingdelegator
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdelegator-0.1.0.tgz
    version: 0.1.0
  pingdevops:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2020-10-22T07:39:46.145664-05:00"
    description: Base Helm Chart for Ping DevOps
    digest: f1aaaba0e6f2f3d977c169d8962a8168d36c227757ec1be4c40b4b11eefc33c5
    home: https://devops.pingidentity.com/
    name: pingdevops
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdevops-0.1.0.tgz
    version: 0.1.0
  pingdirectory:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-22T07:39:46.147427-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDirectory Helm chart
    digest: 70a5936d8fd0423695cabb410a4a02eca4465e95349bc030d09b2dfa4c438d25
    home: https://devops.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-22T07:39:46.146321-05:00"
    description: A Sample PingDirectory Helm chart - CPrice edits
    digest: adbb7295f951cd47ba95442e438d5b33bb2383dc4db9ce01739706919e324293
    home: https://www.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.0.9.tgz
    version: 0.0.9
  pingfederate:
  - apiVersion: v2
    appVersion: 10.1.0
    created: "2020-10-22T07:39:46.149185-05:00"
    dependencies:
    - name: pingdevops
      repository: https://helm.pingidentity.com/devops
      version: 0.1.0
    description: A Sample PingFederate Helm chart with clustering
    digest: 761284b8498538400e73744643c5f9d0738d7c6af13841159fef45892e70e9c6
    home: https://devops.pingidentity.com/
    name: pingfederate
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 10.1.0
    created: "2020-10-22T07:39:46.148139-05:00"
    description: A Sample PingFederate Helm chart with clustering - CPrice Edits
    digest: 5d90e47d7c13cfcc89d36af1bdcd7fab12a5e5c358d707e760cd238f89be7739
    home: https://www.pingidentity.com/
    name: pingfederate
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-0.0.4.tgz
    version: 0.0.4
  pingfederate-admin:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-22T07:39:46.150165-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Admin Helm chart with clustering
    digest: 8bfbb8d1c6966d4409a95809a08977b13f26d5502f3a224421d26ebc1cb62c36
    home: https://devops.pingidentity.com/
    name: pingfederate-admin
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-admin-0.1.0.tgz
    version: 0.1.0
  pingfederate-engine:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-22T07:39:46.151914-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Engine Helm chart with clustering
    digest: ad8e7f5fdef113e659d303c0fd1e409e85e44adda33fb34d5ad4d7d862873425
    home: https://devops.pingidentity.com/
    name: pingfederate-engine
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-engine-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-22T07:39:46.134453-05:00"
