apiVersion: v1
entries:
  pingaccess:
  - apiVersion: v2
    appVersion: "6.1"
    created: "2020-10-23T15:52:34.958441-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingAccess Helm chart
    digest: 518edb7aeb41b0294c6aedea2687b11e5920160cbea3afea4fb28b79d515c9c6
    home: https://devops.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-23T15:52:34.957485-05:00"
    description: A Sample PingAccess Helm chart
    digest: 8b650ce9c728cf778914d2c8cb139caaa6d28ec44a8217ed3df8b9babfda5642
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-23T15:52:34.956997-05:00"
    description: A Sample PingAccess Helm chart
    digest: 7fd4d7051b374fbe14b6556b52bb491838585effa8e518a8a6bb0fb7ffa76d0e
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.5.tgz
    version: 0.0.5
  pingcentral:
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-23T15:52:34.959678-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: b50a6b19705ac0c7d47fbee36965efa748eb78a55df62066325b136076c16699
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-23T15:52:34.959052-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: 152fc218371d853ce5955265f0fea61765d48970484caef72ed04972d8bd7d8e
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.18.tgz
    version: 0.0.18
  pingdataconsole:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-23T15:52:34.960504-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Standalone PingDataConsole Helm chart
    digest: b1e23aa1818e826bb8b3a3291dc2cebba61a6736f561341aa54d16fca3811eaa
    home: https://devops.pingidentity.com/
    name: pingdataconsole
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdataconsole-0.1.0.tgz
    version: 0.1.0
  pingdatasync:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-23T15:52:34.962378-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDataSync Helm chart
    digest: 7ce94ac6316374cd88e257a023eebe25effa9695a811a09ebd0eaf1b4f60cfeb
    home: https://devops.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-23T15:52:34.960985-05:00"
    description: A Sample PingDataSync Helm chart - CPrice edits
    digest: bff337aaacb56464485ada991a36b9f8ed85e6e24251714fe13a6cd940033850
    home: https://www.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.0.3.tgz
    version: 0.0.3
  pingdelegator:
  - apiVersion: v2
    appVersion: "4.2"
    created: "2020-10-23T15:52:34.963335-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDelegator Helm chart
    digest: 0c65b66bbd08234897be5b8f0eb9fecabe6af2ef2380d6774d14f1f73e9df59c
    home: https://devops.pingidentity.com/
    name: pingdelegator
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdelegator-0.1.0.tgz
    version: 0.1.0
  pingdirectory:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-23T15:52:34.965097-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDirectory Helm chart
    digest: 00f64bedeabb0f63881a76f51b9059c072d653125db1c14b1ca3caabfec423cd
    home: https://devops.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-23T15:52:34.96399-05:00"
    description: A Sample PingDirectory Helm chart - CPrice edits
    digest: adbb7295f951cd47ba95442e438d5b33bb2383dc4db9ce01739706919e324293
    home: https://www.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.0.9.tgz
    version: 0.0.9
  pingfederate:
  - apiVersion: v1
    appVersion: 10.1.0
    created: "2020-10-23T15:52:34.966553-05:00"
    description: A Sample PingFederate Helm chart with clustering - CPrice Edits
    digest: 5d90e47d7c13cfcc89d36af1bdcd7fab12a5e5c358d707e760cd238f89be7739
    home: https://www.pingidentity.com/
    name: pingfederate
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-0.0.4.tgz
    version: 0.0.4
  pingfederate-admin:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-23T15:52:34.967521-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Admin Helm chart with clustering
    digest: c62dc7990014acc03895017234f47f522a1da9d479d9aa75b146e546543e210e
    home: https://devops.pingidentity.com/
    name: pingfederate-admin
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-admin-0.1.0.tgz
    version: 0.1.0
  pingfederate-engine:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-23T15:52:34.969588-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Engine Helm chart with clustering
    digest: 0c7ae44bde41490d9169b02a42e53b5f0e736fd0bac44e0db0662274239ef71f
    home: https://devops.pingidentity.com/
    name: pingfederate-engine
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-engine-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-23T15:52:34.955714-05:00"
