apiVersion: v1
entries:
  pingaccess:
  - apiVersion: v2
    appVersion: "6.1"
    created: "2020-10-29T11:15:41.372229-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingAccess Helm chart
    digest: 77347d841554be656f0702596eb5d2d31c455f593915d2d6082e17cab2dc9f5d
    home: https://devops.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-29T11:15:41.370869-05:00"
    description: A Sample PingAccess Helm chart
    digest: 8b650ce9c728cf778914d2c8cb139caaa6d28ec44a8217ed3df8b9babfda5642
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 6.1.0
    created: "2020-10-29T11:15:41.370042-05:00"
    description: A Sample PingAccess Helm chart
    digest: 7fd4d7051b374fbe14b6556b52bb491838585effa8e518a8a6bb0fb7ffa76d0e
    home: https://www.pingidentity.com/
    name: pingaccess
    sources:
    - https://github.com/patrickcping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingaccess-0.0.5.tgz
    version: 0.0.5
  pingcentral:
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-29T11:15:41.373842-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: b50a6b19705ac0c7d47fbee36965efa748eb78a55df62066325b136076c16699
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v1
    appVersion: "1.5"
    created: "2020-10-29T11:15:41.373071-05:00"
    description: A Sample PingCentral Helm chart - based on pingidentity-pc chart
    digest: 152fc218371d853ce5955265f0fea61765d48970484caef72ed04972d8bd7d8e
    home: https://www.pingidentity.com/
    name: pingcentral
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingcentral-0.0.18.tgz
    version: 0.0.18
  pingdataconsole:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-29T11:15:41.375106-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Standalone PingDataConsole Helm chart
    digest: 58ec9b0e922a00b442486cbea93cb32e4b2e62e597b219a4ef6e89c08e38de36
    home: https://devops.pingidentity.com/
    name: pingdataconsole
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdataconsole-0.1.0.tgz
    version: 0.1.0
  pingdatasync:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-29T11:15:41.377047-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDataSync Helm chart
    digest: 5fd1dd869059ab71640f96ab1857db853f39a7fb37d9efc9c42d0ae0b4f551eb
    home: https://devops.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-29T11:15:41.37577-05:00"
    description: A Sample PingDataSync Helm chart - CPrice edits
    digest: bff337aaacb56464485ada991a36b9f8ed85e6e24251714fe13a6cd940033850
    home: https://www.pingidentity.com/
    name: pingdatasync
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdatasync-0.0.3.tgz
    version: 0.0.3
  pingdelegator:
  - apiVersion: v2
    appVersion: "4.2"
    created: "2020-10-29T11:15:41.378594-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDelegator Helm chart
    digest: eb5c05355ecce98aca3ac2649582d219ddf742b288e52fd79e0aaf5b55ab7478
    home: https://devops.pingidentity.com/
    name: pingdelegator
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdelegator-0.1.0.tgz
    version: 0.1.0
  pingdirectory:
  - apiVersion: v2
    appVersion: "8.1"
    created: "2020-10-29T11:15:41.380958-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingDirectory Helm chart
    digest: 708f46d719cfede37835367edfbc5e57604085f188a7a98e0713f0112282f5d7
    home: https://devops.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    appVersion: 8.1.0
    created: "2020-10-29T11:15:41.379457-05:00"
    description: A Sample PingDirectory Helm chart - CPrice edits
    digest: adbb7295f951cd47ba95442e438d5b33bb2383dc4db9ce01739706919e324293
    home: https://www.pingidentity.com/
    name: pingdirectory
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingdirectory-0.0.9.tgz
    version: 0.0.9
  pingfederate:
  - apiVersion: v1
    appVersion: 10.1.0
    created: "2020-10-29T11:15:41.382606-05:00"
    description: A Sample PingFederate Helm chart with clustering - CPrice Edits
    digest: 5d90e47d7c13cfcc89d36af1bdcd7fab12a5e5c358d707e760cd238f89be7739
    home: https://www.pingidentity.com/
    name: pingfederate
    sources:
    - https://github.com/cprice-ping/pingidentity-helm-charts
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-0.0.4.tgz
    version: 0.0.4
  pingfederate-admin:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-29T11:15:41.384039-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Admin Helm chart with clustering
    digest: a09a2b743d7a6f0f6a78e1ee8174181505a4eff57c73b93f6ba5030977c063e6
    home: https://devops.pingidentity.com/
    name: pingfederate-admin
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-admin-0.1.0.tgz
    version: 0.1.0
  pingfederate-engine:
  - apiVersion: v2
    appVersion: "10.1"
    created: "2020-10-29T11:15:41.386621-05:00"
    dependencies:
    - name: pingdevops
      repository: file://../../pingdevops
      version: 0.1.0
    description: A Sample PingFederate Engine Helm chart with clustering
    digest: 9cc5e6efbc86b392a061d9303a7bf5f7283394e9497cf8c12b64ebeed49d1843
    home: https://devops.pingidentity.com/
    name: pingfederate-engine
    sources:
    - https://github.com/pingidentity/pingidentity-getting-started
    - https://github.com/pingidentity/pingidentity-docker-builds
    - https://github.com/pingidentity/pingidentity-server-profiles
    type: application
    urls:
    - https://helm.pingidentity.com/devops/pingfederate-engine-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-29T11:15:41.368274-05:00"
