{{- include "pinglib.workload" (list . "pingdirectory") -}}



{{- define "pingdirectory.workload" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.fullimagename" . }}
{{- end -}}