############################################################
# Ping Identity
#
# Link on deploying with helm:
#   https://pingidentity-devops.gitbook.io/devops/deploy/deployk8s/deployhelm
############################################################

global:
  ############################################################
  #  addReleaseNameToResource: Provides global ability to add
  #                            names to kubernetes resources
  #      <not-set or any val>: No use of Release.Name ** DEFAULT **
  #                    append: Appends the Release.Name
  #                   prepend: Prepends the Release.Name
  ############################################################
  addReleaseNameToResource: prepend

  ############################################################
  # Ingress
  #
  #          ingress.enabled: {true | false}
  # ingress.addReleaseToHost: {prepend | append | subdomain | none}
  #    ingress.defaultDomain: Replaces with "_defaultDomain_" in host fields
  # ingress.defaultTlsSecret: Replaces with "_defaultTlsSecret_" in tls.secretName
  ############################################################
  #ingress:
    #enabled: true
    #addReleaseNameToHost: subdomain
    #defaultDomain: "ping-devops.com"

############################################################
# Ping DevOps Service Customizations
#
# This provides:
#  - PingFederate Administrative Console with native authentication
#  - PingFederate Engines clustered with console
#
# For more environment variables see:
#   https://pingidentity-devops.gitbook.io/devops/dockerimagesref
############################################################
pingfederate-admin:
  chartEnabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingfederate

pingfederate-engine:
  chartEnabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingfederate
